# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: action/checkout@main
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: run deploy.sh
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: npm install && npm run deploy
      - name: run deploy.sh
        uses: findnr/vue-element-plus-temp@main
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: main
          BRANCH: test
          FOLDER: docs/dist
          BUILD_SCRIPT: npm install && npm run build && cd docs/dist && cd -
